### PR TITLE
Colorful Markers. Closes #15.

### PR DESCRIPTION
**Pull request by StefanBrand**
I also changed the appearance of the marker in [line 30](https://github.com/Roboe/fprsmap/compare/gh-pages...newluck77:colorfulMarkers?expand=1#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR30) to use the new blue marker. (I removed the gradient, so it appears flatter.)

### CODE REVIEW

**Comment by Roboe** [comment]
Great!

**Comment by StefanBrand** [comment]
We can also make lighter and darker markers (they just need to be exported).

Am 11.09.2016 um 23:45 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
I think we should wait until #13 is merged, we have enough colors for know, don't you think?

**Comment by StefanBrand** [comment]
I was just mentioning it, in case we want different levels of 
envolvement/topicality (e.g. active/inactive communities) etc...

Am 12.09.2016 um 21:31 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
Oh, I see! Good idea, instead of the color change I proposed, :+1:

**Comment by StefanBrand** [comment]
That's what they teach us in my study... :blush:

Am 12.09.2016 um 21:48 schrieb Roberto M.F.:

**Pull request merged**
